export default {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_SESSION: 'SET_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',
  CLEAN_SIGNUP_IMAGE: 'CLEAN_SIGNUP_IMAGE',
  SET_SIGNUP_IMAGE: 'SET_SIGNUP_IMAGE',
};
